export type Fixture = {
  fixture_id: number;
  fixture_date: string;
  home_team: string;
  away_team: string;
  league_id: number;
  league_name: string;
  venue_id: number | null;
  venue_name: string;
  venue_city: string;
  latitude: number;
  longitude: number;
  distance_miles: number;
  status: string | null;
  home_goals: number | null;
  away_goals: number | null;
  away_day_score: number | null;
  atmosphere_score: number | null;
  review_count: number;
  recommend_percentage: number | null;
  open_to_meet_count: number;
};
